name: Android CI

on: workflow_dispatch
  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Install dependencies
      run: |
        cd test-app/build-tools/jsparser
        npm install

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with V8
      run: ./gradlew -Pengine=V8
    
    - name: Build with QUICKJS
      run: ./gradlew -Pengine=QUICKJS
    
    - name: Build with JSC
      run: ./gradlew -Pengine=JSC
      
    - name: Build with HERMES
      run: ./gradlew -Pengine=HERMES
      
    - name: Upload artifacts
    - uses: actions/upload-artifact@v4
      with:
        name: release
        path: |
          ./dist_v8
          ./dist_jsc
          ./dist_hermes
          ./dist_quickjs

    
