name: Build with Hermes

on: workflow_dispatch
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
  
      - name: Install dependencies
        run: |
          cd test-app/build-tools/jsparser
          npm install
  
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        
      - name: Build with HERMES
        run: ./gradlew -Pengine=HERMES
        
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release
          path: |
            ./dist_hermes

    
